version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./backend/server/.env
  db:
    image: mongo:latest
    container_name: mongopes
    environment:
      MONGO_INITDB_ROOT_USERNAME: newuser
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: testx
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  
  runner:
    build:
      context: ./backend
      dockerfile: DockerfileRunner
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/server/.env
    depends_on:
      - db
      - backend
      - frontend
  processor:
    build:
      context: ./backend
      dockerfile: Dockerfile-process
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/server/.env
    depends_on:
      - db
      - backend
      - frontend

